### ISSUE TITLE
cellshape_cloud and cellshape_cluster throw undefined attribute errors when running following instructions

### ISSUE THREAD

**Issue by caylamiller** [Sentinal4D/cellshape#11]
Hi, I'm trying to run through the instructions with the sample data once before trying on my own data.
I installed following the given instructions (pip installed in clean conda environment), then followed through data download. All good up to that point, but then I've run into a few issues:
1. Train DFN autoencoder
- I first got an error because h5py wasn't installed. 
- After installing that, the train command fails instantly with error "AttributeError: module 'cellshape_cloud' has no attribute 'train_autoencoder'"
I was able to run it after importing the "train_autoencoder" function in the init file for cellshape_cloud. 
2. Add clustering layer to refine shape features and learn shape classes simultaneously
- Training immediately fails again, this time with error "AttributeError: module 'cellshape_cluster' has no attribute 'DeepEmbeddedClustering'". The version of cellshape_cluster that's installed is 0.0.16, and doesn't have any imports in the init file. Adding the imports present in version 0.0.18 cause further errors within deep_embedded_clustering ("No module named 'clustering layer'") and training_functions ("No module named 'distributions'").

**Comment by Shannon-E-Taylor** [comment]
It runs for me :D - though I also had to install torch and reduce the `batch_size` to 2 to get it to run on my GPU (RTX3050)

**Comment by caylamiller** [comment]
I just got a chance to retry and was able to run as well, thanks for updating!

**Comment by DeVriesMatt** [comment]
Glad it's all working! :smile:
